query getQuestionsByQuizId($quiz_id: ID!) {
  getQuestionsByQuizId(quiz_id: $quiz_id) {
    _id
    question_content
    question_answers {
      answer_content
      answer_isCorrect
    }
    question_scores
    question_times
  }
}
