mutation updateQuestionById(
  $_id: ID!
  $question_content: String
  $question_answers: [AnswersInput]
  $question_scores: Int
  $question_times: Int
) {
  updateQuestionById(
    _id: $_id
    question_content: $question_content
    question_answers: $question_answers
    question_scores: $question_scores
    question_times: $question_times
  ) {
    _id
    question_content
    question_answers {
      answer_content
      answer_isCorrect
    }
    question_scores
    question_times
  }
}
