mutation updateQuestionById(
  $_id: ID!
  $question_content: String
  $question_answers: [AnswerInput]
) {
  updateQuestionById(
    _id: $_id
    question_content: $question_content
    question_answers: $question_answers
  ) {
    _id
    question_content
    question_answers {
      answer_content
      answer_isCorrect
    }
  }
}
